README.md

Linked to ADOT Public Preview Program details.

Added ADOT Public Preview Program info

---

README.md

Added section for filing issues and PRs to ADOT Tech Docs site.

Added ADOT Tech Docs site info

---

sample-configs/operator/collector-config-advanced.yaml
sample-configs/operator/collector-config-amp.yaml
sample-configs/operator/collector-config-cloudwatch.yaml
sample-configs/operator/collector-config-xray.yaml

This PR updates the configs for the [Getting Started Guide](https://aws-otel.github.io/docs/getting-started/adot-eks-add-on). Updates include:
* Add batch processor to advanced config
* Change Collector names to be different between configs
* Add comments to AMP and CW configs

Getting Started Guide Configs Update

---

preview-program/README.md

Description:
Updates the preview program README

Update preview program

---

sample-configs/operator/collector-config-xray.yaml
sample-configs/sample-app.yaml

Description:
This PR updates the sample app image in the sample-configs

Update the sample app provided in the sample configs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/general-issue.md
README.md

Add best effort verbiage to issue templates

Add issue template best effort policy

---

sample-configs/operator/collector-config-xray.yaml

Fix operator kind

---

sample-apps/java-sample-app/auto/src/main/resources/log4j2.xml

Description:
Modify log format in the auto sample application so that it is compatible with Service Lens: https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-logging

Modify log format in the auto sample application

---

sample-apps/java-sample-app/auto/src/main/resources/log4j2.xml

Description:
Fix typo in the log format for the java sample application

Fix typo in log format for java sample app

---

README.md

Add security issue notification blurb to readme

---

sample-apps/java-sample-app/README.md
sample-apps/java-sample-app/auto/build.gradle.kts
sample-apps/java-sample-app/auto/src/main/resources/log4j2.xml
sample-apps/java-sample-app/base/build.gradle.kts
sample-apps/java-sample-app/cw-agent.json
sample-apps/java-sample-app/extension/build.gradle.kts
sample-apps/java-sample-app/extension/src/main/java/software/amazon/adot/sampleapp/extension/Configurer.java
sample-apps/java-sample-app/manual/build.gradle.kts
sample-apps/java-sample-app/manual/src/main/java/software/amazon/adot/sampleapp/AwsXrayContextDataProvider.java
sample-apps/java-sample-app/manual/src/main/java/software/amazon/adot/sampleapp/ManualApp.java
sample-apps/java-sample-app/manual/src/main/resources/META-INF/services/org.apache.logging.log4j.core.util.ContextDataProvider
sample-apps/java-sample-app/manual/src/main/resources/log4j2.xml
sample-apps/java-sample-app/settings.gradle.kts

Signed-off-by: Raphael Silva <rapphil@gmail.com>
Description: Add example of how log correlation can be setup with Java.

Add example of how setup log correlation in the Java sample app.

---

sample-apps/prometheus-sample-app/Dockerfile

Description:  The purpose of this PR is to resolve the container image build failure resulting from attempting to build the Prometheus sample application in this repository.
Link to tracking Issue: #257 
```bash
cd ./sample-apps/prometheus
docker build . -t prometheus-sample-app:latest
```
results in a successfully built image.

Update prometheus sample app to go 1.17 image

---

sample-apps/SampleAppSpec.md

Description: Update the sample app spec with test assertions and other edits.

Update the sample app spec

---

sample-apps/README.md
sample-apps/go-sample-app/README.md
sample-apps/java-sample-app/README.md
sample-apps/javascript-sample-app/README.md
sample-apps/python-auto-instrumentation-sample-app/README.md
sample-apps/python-manual-instrumentation-sample-app/README.md

Description: Updated the documentation in the READMEs for the standardized sample apps.

Update documentation for the standardized sample apps

---

.github/workflows/integration-test.yml

Description: Change region to us-east-1 to login into ECR during workflow

Change region to us-east-1

---

.github/workflows/centralized-sampling-tests.yml
.github/workflows/integration-test.yml

Update version of `configure-aws-credentials` action

[chore] Update configure-aws-credentials versions

---

sample-apps/python-auto-instrumentation-sample-app/requirements.txt

Description: Update the Python auto instrumentation sample app dependencies to fix workflow.
Testing Performed: Local testing passed.

Update the Python Auto Dep

---

.github/workflows/integration-test.yml

*Description of changes:*
updating workflows to upgrade to node.js 16
*Tracking Issue:*
https://github.com/aws-observability/aws-otel-community/issues/435

updating workflows to upgrade to node.js 16

---

sample-apps/python-auto-instrumentation-sample-app/requirements.txt
sample-apps/python-manual-instrumentation-sample-app/requirements.txt

Description:
This PR upgrades `flask` versions in `python manual instrumentation sample app` and `python auto instrumentation sample app`

Upgrade flask to 2.2.5

---

sample-apps/javascript-sample-app/package-lock.json
sample-apps/javascript-sample-app/package.json

Description: https://stackoverflow.com/questions/70541068/instead-change-the-require-of-index-js-to-a-dynamic-import-which-is-available

Pin node-fetch to major version 2.x.x

---

sample-apps/javascript-sample-app/random-metrics.js

Description:
Resolving CI failure in JS sample app due to GRPC Metric Exporter
Link to tracking Issue: CI Failure
Testing Performed: manual testing on local box

Resolving CI failure in JS app due to GRPC Metric Exporter

---

sample-apps/python-auto-instrumentation-sample-app/requirements.txt

Description:
Dependabot dependency updates - python auto sample app

Dependabot dependency updates - python auto sample app

---

sample-apps/java-sample-app/base/build.gradle.kts
sample-apps/java-sample-app/extension/build.gradle.kts
sample-apps/java-sample-app/manual/build.gradle.kts

Description:
Bumps:
https://github.com/aws-observability/aws-otel-community/pull/497
https://github.com/aws-observability/aws-otel-community/pull/414/files
https://github.com/aws-observability/aws-otel-community/pull/413/files
https://github.com/aws-observability/aws-otel-community/pull/273/files
Testing Performed: Manual testing on local

java-sample-app dependency updates

---

sample-configs/traffic-generator.yaml

fix service name

---

.github/dependabot.yml

Description: Group dependabot PRs for each sample app in accordance with new group update to make merging community dependabots easier.

Add dependabot PR groups for each sample app

---

sample-apps/java-sample-app/auto/build.gradle.kts

Description: Update the Java agent version in the jvm args to match the updated java agent dependency.

Update java agent version in jvm args

---

sample-apps/java-sample-app/auto/build.gradle.kts

Description: Align java versions used in java agent auto instrumented sample app

fix java versions

---

sample-apps/python-auto-instrumentation-sample-app/requirements.txt
sample-apps/python-manual-instrumentation-sample-app/requirements.txt

Description: Rollback version until pack release is resolved and finalized upstream. Refer to these issues upstream.
https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1938
https://github.com/open-telemetry/opentelemetry-python-contrib/issues/1935

Rollback python version

---

.github/dependabot.yml

Description: Add dependabot update group for dotnet sample app.

Add dependabot update for .net

---

centralized-sampling-tests/sample-apps/spring-boot/src/main/java/com/amazon/sampleapp/AppController.java
sample-apps/java-sample-app/manual/build.gradle.kts
sample-apps/java-sample-app/manual/src/main/java/software/amazon/adot/sampleapp/ManualApp.java

Description: Fix the java dependency updates to fix workflow.

Fix java dependency updates

---

sample-apps/python-auto-instrumentation-sample-app/requirements.txt

Reverts aws-observability/aws-otel-community#731

Revert "Bump the python-auto-sample-app-deps group in /sample-apps/python-auto-instrumentation-sample-app with 3 updates"

---

sample-apps/python-manual-instrumentation-sample-app/requirements.txt

Reverts aws-observability/aws-otel-community#772

Revert "Bump the python-manual-sample-app-deps group in /sample-apps/python-manual-instrumentation-sample-app with 3 updates"

---

centralized-sampling-tests/README.md
sample-apps/dotnet-sample-app/docker-compose.yml

Description:
Change path for aws creds to non root user

Change path for aws creds to non root user

---

sample-apps/dotnet-sample-app/dotnet-sample-app.csproj

Update dependencies that are missed in - https://github.com/aws-observability/aws-otel-community/pull/926

[dotnet]-Missed dependabot updates

---

.github/CODEOWNERS

Description:
Update codeowners file for sample apps

Update codeowners file for sample apps

---

.github/labeler.yml
.github/workflows/labeler.yml

In this commit, we are adding a labelling workflow using Labeler, which will add a helpful label to sample-app-related PRs
Testing done in a fork:
* https://github.com/thpierce/aws-otel-community/pull/14
* https://github.com/thpierce/aws-otel-community/pull/15
* https://github.com/thpierce/aws-otel-community/pull/16
* https://github.com/thpierce/aws-otel-community/pull/17

Add Labeler

---

.github/workflows/integration-test.yml

Update integration-test.yml to use new metering role ARN

---

.github/workflows/integration-test.yml

Align metrics with other Repos
