sample-configs/operator/collector-config-cloudwatch.yaml

Update to the CloudWatch configuration to provide default list of `metric_name_selectors`, to reduce steps in applying configuration

Update CW config with list of `metric_name_selectors`

---

sample-configs/operator/collector-config-amp.yaml

Changing serviceAccount: adot-demo to serviceAccount: adot-collector to be consistent between YAML files, the ADOT getting started guide (https://aws-otel.github.io/docs/getting-started/adot-eks-add-on), and the EKS docs (https://docs.aws.amazon.com/eks/latest/userguide/deploy-collector.html).

Update collector-config-amp.yaml with serviceAccount: adot-collector

---

sample-configs/operator/collector-config-cloudwatch.yaml

Changing serviceAccount: adot-demo to serviceAccount: adot-collector to be consistent between YAML files, the ADOT getting started guide (https://aws-otel.github.io/docs/getting-started/adot-eks-add-on), and the EKS docs (https://docs.aws.amazon.com/eks/latest/userguide/deploy-collector.html).

Update collector-config-cloudwatch.yaml with serviceAccount: adot-collector

---

sample-configs/operator/collector-config-xray.yaml

Changing serviceAccount: adot-demo to serviceAccount: adot-collector to be consistent between YAML files, the ADOT getting started guide (https://aws-otel.github.io/docs/getting-started/adot-eks-add-on), and the EKS docs (https://docs.aws.amazon.com/eks/latest/userguide/deploy-collector.html).

Update collector-config-xray.yaml with serviceAccount: adot-collector

---

sample-configs/operator/collector-config-cloudwatch.yaml

Added missing Amazon branding to CloudWatch as shown in:
https://docs.aws.amazon.com/eks/latest/userguide/configure-cw.html

Update CW config with missing Amazon branding

---

sample-configs/operator/collector-config-cloudwatch.yaml

Second instance of adot-demo needs to be changed to adot-collector.
Description:

Update collector-config-cloudwatch.yaml - 2nd instance of adot-demo also needs to be updated

---

sample-configs/operator/collector-config-cloudwatch.yaml

Second instance of adot-demo needs to be changed to adot-collector.
Description:

Update collector-config-cloudwatch.yaml - 2nd instance of adot-demo needs to be changed

---

sample-configs/operator/collector-config-amp.yaml

Description:
Fixed service account in cluster role binding to point to the adot-collector service account which is created in previous steps.
Created a new EKS cluster and AMP workspace with fixed yaml for collector CRD and confirmed metrics ingestion into AMP instance through AMG dashboards. 

Incorrect service account in ClusterRoleBinding

---

sample-configs/operator/collector-config-advanced.yaml
sample-configs/operator/collector-config-amp.yaml

Description:
This PR removes references to the awsprometheusremotewrite exporter following the removal of it in v0.21.0 of the ADOT Collector.

Remove references to the `awsprometheusremotewrite` exporter

---

sample-apps/python-auto-instrumentation-sample-app/requirements.txt

Description:
This PR updates the OTEL-Python to `1.12.0` and 0.33b0 contrib dependencies

Update stable opentelemetry-Python dependencies 1.12.0 and 0.33.b0

---

sample-apps/java-sample-app/base/build.gradle.kts

Fix missing logging dependency that was causing warning message:
```
logger - opentelemetry-javaagent - version: 1.17.0-aws
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See 
```

Add missing dependency

---

sample-configs/operator/collector-config-amp.yaml
sample-configs/operator/collector-config-cloudwatch.yaml
sample-configs/operator/collector-config-xray.yaml

Signed-off-by: Raphael Silva <rapphil@gmail.com>
Description: Update examples so that they can be run reliably in EKS with Fargate. EKS with fargate nodes have default CPU set in 0.25vCPU. This is not enough to run these examples. On top of that, Fargate requires that limits and requests to be set to the same value.

Update examples for fargate

---

.github/workflows/centralized-sampling-tests.yml
centralized-sampling-tests/collector-config.yml
centralized-sampling-tests/docker-compose-golang-app.yml
centralized-sampling-tests/docker-compose-integration-tests.yml
centralized-sampling-tests/docker-compose-java-app.yml
centralized-sampling-tests/example-collector-config.yaml

Description:
Split `sample app` from the main docker-compose (which contains `otel collector` and `integration tests`).
This is to reuse the main docker-compose file for multiple sample apps that will be added in the future.
Also change OTel Collector loglevel to "error" to reduce load on OTel Collector.
Testing Performed: [GH Workflow](https://github.com/jj22ee/aws-otel-community/actions/runs/4681582295/jobs/8294349307)

Modularize docker compose files for Centralize Sampling sample apps

---

centralized-sampling-tests/integration-tests/src/main/java/com.amazon.tests/CentralizedSamplingIntegrationTests.java
centralized-sampling-tests/integration-tests/src/main/java/com.amazon.tests/GenericConstants.java
centralized-sampling-tests/integration-tests/src/main/java/com.amazon.tests/SampleRules.java
centralized-sampling-tests/integration-tests/src/main/java/com.amazon.tests/testCases.java
centralized-sampling-tests/sample-apps/spring-boot/build.gradle
centralized-sampling-tests/sample-apps/spring-boot/src/main/java/com/amazon/sampleapp/AppController.java

Description:
Update Integration Test cases
- Span name is now constant
- Updated XRay Sampler dependency so that the OTel Resource Service Name is used to determine Sampling Rule
- Service name rule is moved out from priority test case as the OTel Resource Service Name is also constant
Testing Performed: [GH Workflow](https://github.com/jj22ee/aws-otel-community/actions/runs/4683878554)

Update Centralized Sampling integration tests and Java sample app

---

sample-apps/javascript-sample-app/nodeSDK.js
sample-apps/javascript-sample-app/package.json

The `opentelemetry-instrumentation-aws-sdk` package currently in use in the javascript-sample-app has been [deprecated in favor of @opentelemetry/instrumentation-aws-sdk](https://www.npmjs.com/package/opentelemetry-instrumentation-aws-sdk) and is producing traces with outdated names and attributes 
Example: DynamoDB span has the following name instead of `DynamoDB`
```
"{\"name\":\"dynamodb.us-west-2.amazonaws.com\"}
```
Instead, we should be using the [@opentelemetry/instrumentation-aws-sdk package](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/package.json#L2) to ensure the Javascript sample app is producing the correct trace data for the `/aws-sdk-call` endpoint and that any upstream changes to the AWS SDK …

Fix deprecated opentelemetry-instrumentation-aws-sdk package in javascript sample app

---

sample-apps/javascript-sample-app/request-metrics.js

Description:
Resolving Current Integration test failure in JS Sample app in request based metrics. Previous PR fixed it in only random metrics: https://github.com/aws-observability/aws-otel-community/pull/506
Link to tracking Issue:CI Failure Alarm
Testing Performed: Manually on local box

Resolving current metric related js sample app integ test failure

---

sample-apps/javascript-sample-app/nodeSDK.js

As far as I can tell, this is the more correct statement.
Even [the docs](https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr#instrumenting-the-aws-sdk) show this usage.
N/A
N/A

Update package for AWS Instrumentation

---

sample-apps/javascript-sample-app/package.json

Description: The group PR updated the node-fetch dependency but it should not be updated as the update would require the node-fetch dep to be imported to as an ES module.

Revert node-fetch dep to fix JS sample app

---

centralized-sampling-tests/integration-tests/build.gradle
centralized-sampling-tests/sample-apps/spring-boot/build.gradle

Description: Revert dependency management version which was leading to errors within the build to find dependencies.  This was working with version `1.1.0` and so this could be a due to a bug in the newest version `1.1.1` that was just released very recently.

Revert dependency management version

---

sample-apps/java-sample-app/auto/build.gradle.kts

Description: Remove the need to explicitly set the java agent version in parameters that cannot be updated by dependabot.
This will allow the command line parameter and the dependency to remain aligned.

Fix: remove the need to explicitly define the version in gradle script

---

.github/dependabot.yml
sample-apps/python-manual-instrumentation-sample-app/requirements.txt

Description:
`Flask==3.0.0`  is not included in [opentelemetry-instrumentation-flask](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/eb6024ca3171072daa5d842d9363e41d72ee64a6/instrumentation/opentelemetry-instrumentation-flask/pyproject.toml#L38) yet and hence leading to the failures for this major upgrade. Hence ignoring the upgrade.

Ignore Flask major upgrades in dependabot

---

sample-apps/python-auto-instrumentation-sample-app/app.py

Description: We were experiencing an issue with Flask instrumentation after we were not seeing the correct spans being produced in the python-auto-instrumentation-sample-app.  Explicitly defining the Flask instrumentation fixes this issue.
Testing Performed: Test passed locally.

Add Flask instrumentation explicitly in Python Auto Instrumentation

---

sample-apps/dotnet-sample-app/README.md
sample-apps/dotnet-sample-app/dotnet-sample-app.csproj
sample-apps/javascript-sample-app/server.js

Description: The JS sample app required tweaking to the if conditional to perform the HTTP call.  For dotnet, the error is stemming from the update to the HTTP instrumentation that is due to the new semantic conventions.
Testing Performed: Local testing

Fix the sample apps for integration tests

---

sample-apps/README.md

Description: Fix the README to point to the right sample app for Ruby.

Fix README for Ruby sample app

---

sample-apps/dotnet-sample-app/dotnet-sample-app.csproj

Reverts aws-observability/aws-otel-community#928. and https://github.com/aws-observability/aws-otel-community/pull/926 .

Revert "[dotnet]-Missed dependabot updates"

---

.github/workflows/integration-test.yml

Failures: https://github.com/aws-observability/aws-otel-community/actions/runs/10411844454/job/28836523928
See https://github.com/orgs/community/discussions/116610

Fix docker-compose in integ tests

---

.github/workflows/integration-test.yml

Change `Success` metrics to `Failure` metrics, for easier monitoring.

Align failure metrics with existing metrics

---

sample-configs/operator/collector-config-amp.yaml

Description: When applying collector-config-amp.yaml, all variables in the yaml need to have double $ signs ($$var). However, one line managed to sneak in, causing parsing errors in the collector pods:
```
Error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
2025/02/04 18:38:44 application run finished with error: failed to resolve config: cannot resolve the configuration: cannot convert the confmap.Conf: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
```
Testing Performed: 
`kubectl apply -f collector-config-amp.yaml` returns the above error in the collector pods. Dashboards aren't populated until …

Updating variable declaration in collector-config-amp.yaml
